# Generated by Django 3.1 on 2022-10-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Firs_Name',
            new_name='First_Name',
        ),
    ]
