# Generated by Django 3.1 on 2022-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
